version: '3.6'

# Networks
networks:
  internal:
    name: internal

# Volumes
volumes:
  db_data:
    name: db_data
  bpmloggenerator_data:
    name: bpmloggenerator_data

services:
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal
    env_file: ./.env

  bpmloggenerator:
    build: .
    container_name: bpmloggenerator
    restart: unless-stopped
    volumes:
      - bpmloggenerator_data:/data
    networks:
      - internal
    env_file: ./.env
