# Generated by Django 3.2.6 on 2021-12-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VariabilityTraceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField()),
                ('scenario', models.CharField(max_length=10)),
                ('case_variation_id', models.IntegerField()),
                ('activity', models.CharField(max_length=10)),
                ('variant', models.CharField(max_length=10)),
                ('function_name', models.CharField(max_length=255)),
                ('gui_element', models.CharField(max_length=255)),
            ],
        ),
    ]
