# Generated by Django 3.2.6 on 2021-12-21 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario_id', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('balance', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VariabilityConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('is_scenario', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VariabilityFunctionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.variabilityfunctioncategory', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Variability function category',
                'verbose_name_plural': 'Variability function categories',
            },
            managers=[
                ('tree', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VariabilityFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=255)),
                ('function_name', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('variability_function_category', models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.variabilityfunctioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='UILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('execution_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.executionresult')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('execution_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.executionresult')),
            ],
        ),
        migrations.CreateModel(
            name='GUIComponentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.guicomponentcategory', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'GUI component category',
                'verbose_name_plural': 'GUI component categories',
            },
            managers=[
                ('tree', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GUIComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('gui_component_category', models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.guicomponentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('function_name', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.AddField(
            model_name='executionresult',
            name='generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.generator'),
        ),
        migrations.CreateModel(
            name='ExecutionConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.generator')),
            ],
        ),
    ]
